updates:
    - cooldown:
          default-days: 14

      directories:
          - /

      # This consolidates updates into a maximum of 2 PRs.
      # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates
      groups:
          major:
              update-types:
                  - major

          minor-and-patch:
              update-types:
                  - minor
                  - patch

      package-ecosystem: github-actions

      schedule:
          day: monday
          interval: weekly
          time: "20:00"
          timezone: Europe/London

    - cooldown:
          default-days: 14
          semver-major-days: 30
          semver-minor-days: 14
          semver-patch-days: 7

      directory: /javascript/

      # This consolidates updates into a maximum of 2 PRs.
      # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates
      groups:
          major:
              update-types:
                  - major

          minor-and-patch:
              update-types:
                  - minor
                  - patch

      package-ecosystem: npm

      schedule:
          day: monday
          interval: weekly
          time: "20:00"
          timezone: Europe/London

    - cooldown:
          default-days: 14
          semver-major-days: 30
          semver-minor-days: 14
          semver-patch-days: 7

      directory: /csharp/

      # This consolidates updates into a maximum of 2 PRs.
      # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates
      groups:
          major:
              update-types:
                  - major

          minor-and-patch:
              update-types:
                  - minor
                  - patch

      package-ecosystem: nuget

      schedule:
          day: monday
          interval: weekly
          time: "20:00"
          timezone: Europe/London

    - cooldown:
          default-days: 14
          semver-major-days: 30
          semver-minor-days: 14
          semver-patch-days: 7

      directory: /python/

      # This consolidates updates into a maximum of 2 PRs.
      # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates
      groups:
          major:
              update-types:
                  - major

          minor-and-patch:
              update-types:
                  - minor
                  - patch

      package-ecosystem: pip

      schedule:
          day: monday
          interval: weekly
          time: "20:00"
          timezone: Europe/London

version: 2
